window.MODULES = [
  {
    "label": "EN-TÊTE AVEC LOGO CLIQUABLE",
    "html": "<tr>\n            <td style=\"background-color: #8dd3f6; padding: 0;\">\n              <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"display: block; text-align: center; padding: 20px 20px 15px 20px;\">\n                <img src=\"https://scienceouverte.unistra.fr/websites/_processed_/6/7/csm_Logo_cafes_SO_COURT_542485d502.jpg\" alt=\"Logo de l'Université de Strasbourg\" style=\"display: block; margin: 0 auto; max-width: 150px; height: auto; border: 0;\" width=\"150\" />\n              </a>\n            </td>\n          </tr>"
  },
  {
    "label": "TITRE PRINCIPAL + SOUS-TITRE",
    "html": "<tr>\n            <td style=\"padding: 25px 30px 10px 30px; text-align: center;\">\n              <h1 style=\"margin: 0; font-size: 22px; font-weight: 700; color: #003366; line-height: 1.3;\">\n                [VOTRE TITRE PRINCIPAL]\n              </h1>\n              <p style=\"margin: 5px 0 0 0; font-size: 14px; color: #555555; font-weight: 400;\">\n                [SOUS-TITRE OU PRÉSENTATION DU SERVICE]\n              </p>\n            </td>\n          </tr>"
  },
  {
    "label": "TITRE DE SECTION",
    "html": "<tr>\n            <td style=\"padding: 30px 30px 10px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                [TITRE DE LA SECTION]\n              </h2>\n            </td>\n          </tr>"
  },
  {
    "label": "BLOC DE TEXTE STANDARD",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <p style=\"margin: 0 0 15px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                [VOTRE TEXTE ICI. Vous pouvez utiliser <b>le gras</b>, <i>l'italique</i>, ou <a href=\"https://exemple.com\" target=\"_blank\" rel=\"noopener\">des liens hypertextes</a>.]\n              </p>\n            </td>\n          </tr>"
  },
  {
    "label": "SÉPARATEUR VISUEL",
    "html": "<tr>\n            <td style=\"padding: 20px 30px;\">\n              <hr style=\"border: none; border-top: 1px solid #e0e0e0;\" />\n            </td>\n          </tr>"
  },
  {
    "label": "BOUTON D'ACTION (CTA)",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                <tr>\n                  <td align=\"center\" style=\"background-color: #003366; border-radius: 6px;\">\n                    <a href=\"https://exemple.com\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 12px 28px; font-size: 15px; font-weight: 600; color: #ffffff; text-decoration: none; border-radius: 6px;\">\n                      [TEXTE DU BOUTON]\n                    </a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "ENCADRÉ D'INFORMATION",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px;\">\n                <tr>\n                  <td style=\"padding: 15px;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                      [TITRE DE L'ÉVÉNEMENT OU DE LA SESSION]\n                    </p>\n                    <p style=\"margin: 0 0 5px 0; font-size: 14px; color: #555555;\">\n                      Date : [Date] | Horaire : [Horaire] | Lieu : [Lieu / En ligne]\n                    </p>\n                    <p style=\"margin: 0; font-size: 14px; color: #555555;\">\n                      [Description courte ou contexte]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "IMAGE ILLUSTRATIVE (PLEINE LARGEUR)",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n                <tr>\n                  <td align=\"center\">\n                    <img src=\"https://picsum.photos/540/300?random=1\" alt=\"Image illustrative de la newsletter\" style=\"display: block; max-width: 100%; height: auto; border-radius: 6px;\" width=\"540\" />\n                    <p style=\"margin: 8px 0 0 0; font-size: 12px; color: #999999; text-align: center;\">\n                      [Légende optionnelle]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "TEXTE EN EXERGUE (PLEINE LARGEUR)",
    "html": "<tr>\n            <td style=\"padding: 0 0 15px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #e8f4fd; border-radius: 6px;\">\n                <tr>\n                  <td style=\"padding: 15px 30px;\">\n                    <p style=\"margin: 0; font-size: 15px; color: #003366; font-weight: 600; line-height: 1.5;\">\n                      ATTENTION : [VOTRE MESSAGE EN EXERGUE]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "LISTE À PUCES",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <p style=\"margin: 0 0 10px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                Voici les points à retenir :\n              </p>\n              <ul style=\"margin: 0 0 15px 20px; padding: 0; font-size: 15px; color: #333333; line-height: 1.8;\">\n                <li>[Premier élément de la liste]</li>\n                <li>[Deuxième élément de la liste]</li>\n                <li>[Troisième élément de la liste]</li>\n              </ul>\n            </td>\n          </tr>"
  },
  {
    "label": "SIGNATURE SIMPLE",
    "html": "<tr>\n            <td style=\"padding: 25px 30px 10px 30px;\">\n              <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777;\">\n                Au plaisir de vous retrouver, et en vous souhaitant une agréable semaine,<br />\n                Bien cordialement,\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                [Prénom] [Nom]\n              </p>\n              <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555; line-height: 1.5;\">\n                [Votre fonction / titre]\n              </p>\n              <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                Tel. : [+33 (0)X XX XX XX XX] | <a href=\"mailto:[adresse@unistra.fr]\" style=\"color: #003366; text-decoration: none;\">[adresse@unistra.fr]</a>\n              </p>\n            </td>\n          </tr>"
  },
  {
    "label": "SIGNATURE DOUBLE",
    "html": "<tr>\n            <td style=\"padding: 25px 30px 10px 30px;\">\n              <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777;\">\n                Au plaisir de vous retrouver, et en vous souhaitant une agréable semaine,<br />\n                Bien cordialement,\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                [Prénom 1] [Nom 1] & [Prénom 2] [Nom 2]\n              </p>\n              <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555; line-height: 1.5;\">\n                <i>Respectivement :</i><br />\n                [Fonction 1] <br />\n                [Fonction 2]\n              </p>\n              <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                <a href=\"mailto:[adresse@unistra.fr]\" style=\"color: #003366; text-decoration: none;\">[adresse@unistra.fr]</a>\n              </p>\n            </td>\n          </tr>"
  },
  {
    "label": "SIGNATURE AVEC PHOTO",
    "html": "<tr>\n            <td style=\"padding: 25px 30px 10px 30px;\">\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n                <tr>\n                  <!-- Photo -->\n                  <td width=\"80\" valign=\"top\" style=\"padding-right: 20px;\">\n                    <img src=\"https://picsum.photos/80/80?random=2\" alt=\"Photo de [Prénom] [Nom]\" style=\"display: block; width: 80px; height: 80px; border-radius: 50%; object-fit: cover;\" width=\"80\" height=\"80\" />\n                  </td>\n                  <!-- Infos -->\n                  <td valign=\"top\">\n                    <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777;\">\n                      Au plaisir de vous retrouver, et en vous souhaitant une agréable semaine,<br />\n                      Bien cordialement,\n                    </p>\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                      [Prénom] [Nom]\n                    </p>\n                    <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555; line-height: 1.5;\">\n                      [Votre fonction / titre]\n                    </p>\n                    <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                      Tel. : [+33 (0)X XX XX XX XX] | <a href=\"mailto:[adresse@unistra.fr]\" style=\"color: #003366; text-decoration: none;\">[adresse@unistra.fr]</a>\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "DEUX COLONNES",
    "html": "<tr>\n            <td style=\"padding: 0 30px 15px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n                <tr>\n                  <!-- Colonne gauche -->\n                  <td width=\"48%\" valign=\"top\" style=\"background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px; padding: 15px;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                      [TITRE COLONNE GAUCHE]\n                    </p>\n                    <p style=\"margin: 0; font-size: 14px; color: #555555; line-height: 1.5;\">\n                      [Contenu de la colonne gauche]\n                    </p>\n                  </td>\n                  <!-- Espace entre colonnes -->\n                  <td width=\"4%\"></td>\n                  <!-- Colonne droite -->\n                  <td width=\"48%\" valign=\"top\" style=\"background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px; padding: 15px;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                      [TITRE COLONNE DROITE]\n                    </p>\n                    <p style=\"margin: 0; font-size: 14px; color: #555555; line-height: 1.5;\">\n                      [Contenu de la colonne droite]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "RAPPEL / DEADLINE",
    "html": "<tr>\n            <td style=\"padding: 0 0 15px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #fff8e1; border-radius: 6px;\">\n                <tr>\n                  <td style=\"padding: 15px 30px;\">\n                    <p style=\"margin: 0; font-size: 15px; color: #333333; line-height: 1.5;\">\n                      RAPPEL : [la date limite est le …]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "ARTICLE NEWSLETTE (IMAGE + TEXTE)",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                <tr>\n                  <!-- Image -->\n                  <td width=\"180\" valign=\"top\" style=\"padding-right: 20px;\">\n                    <img src=\"https://picsum.photos/180/120?random=3\" alt=\"Image de l'article\" style=\"display: block; width: 180px; height: 120px; object-fit: cover; border-radius: 6px;\" width=\"180\" height=\"120\" />\n                  </td>\n                  <!-- Texte -->\n                  <td valign=\"top\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 16px; font-weight: 600; color: #003366;\">\n                      [TITRE DE L'ARTICLE]\n                    </p>\n                    <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #555555; line-height: 1.5;\">\n                      [Court résumé de l'article ou de l'actualité. Vous pouvez inclure <a href=\"https://exemple.com\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: underline;\">un lien vers l'article complet</a>.]\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                      <tr>\n                        <td align=\"center\" style=\"background-color: #003366; border-radius: 4px;\">\n                          <a href=\"https://exemple.com\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 8px 16px; font-size: 13px; font-weight: 600; color: #ffffff; text-decoration: none; border-radius: 4px;\">\n                            Lire la suite\n                          </a>\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "LIENS RAPIDES / RESSOURCES",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Ressources complémentaires\n              </h2>\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                <tr>\n                  <td style=\"padding: 5px 0;\">\n                    <a href=\"https://exemple1.com\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none; font-size: 15px;\">\n                      [Titre du lien 1]\n                    </a>\n                  </td>\n                </tr>\n                <tr>\n                  <td style=\"padding: 5px 0;\">\n                    <a href=\"https://exemple2.com\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none; font-size: 15px;\">\n                      [Titre du lien 2]\n                    </a>\n                  </td>\n                </tr>\n                <tr>\n                  <td style=\"padding: 5px 0;\">\n                    <a href=\"https://exemple3.com\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none; font-size: 15px;\">\n                      [Titre du lien 3]\n                    </a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "CITATION / PENSÉE",
    "html": "<tr>\n            <td style=\"padding: 0 0 20px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #f9f9f9; border-left: 4px solid #003366; border-radius: 4px;\">\n                <tr>\n                  <td style=\"padding: 15px 30px;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; color: #333333; font-style: italic; line-height: 1.5;\">\n                      [Votre citation ou pensée du mois]\n                    </p>\n                    <p style=\"margin: 0; font-size: 13px; color: #777777;\">\n                      — [Auteur de la citation]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "DOCUMENT JOINT",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #f0f5ff; border-radius: 8px; overflow: hidden;\">\n                <tr>\n                  <!-- Icône document -->\n                  <td width=\"60\" valign=\"top\" style=\"padding: 20px 15px 20px 20px; text-align: center;\">\n                    <img src=\"https://cdn-icons-png.flaticon.com/512/337/337946.png\" alt=\"Document\" style=\"display: block; width: 48px; height: 48px;\" width=\"48\" height=\"48\" />\n                  </td>\n                  <!-- Contenu -->\n                  <td valign=\"top\" style=\"padding: 20px 20px 20px 0;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                      Document joint : [Nom du document]\n                    </p>\n                    <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #555555;\">\n                      [Description courte du document joint]\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                      <tr>\n                        <td align=\"center\" style=\"background-color: #003366; border-radius: 4px;\">\n                          <a href=\"https://exemple.com/document.pdf\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 8px 16px; font-size: 13px; font-weight: 600; color: #ffffff; text-decoration: none; border-radius: 4px;\">\n                            Télécharger le document\n                          </a>\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "DOCUMENT EN LIGNE",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;\">\n                <tr>\n                  <!-- Image du document -->\n                  <td width=\"180\" valign=\"top\">\n                    <a href=\"https://exemple.com/document\" target=\"_blank\" rel=\"noopener\">\n                      <img src=\"https://picsum.photos/180/120?random=4\" alt=\"Aperçu du document\" style=\"display: block; width: 100%; height: 120px; object-fit: cover;\" width=\"180\" height=\"120\" />\n                    </a>\n                  </td>\n                  <!-- Texte -->\n                  <td valign=\"top\" style=\"padding: 15px;\">\n                    <p style=\"margin: 0 0 5px 0; font-size: 16px; font-weight: 600; color: #003366;\">\n                      [Titre du document en ligne]\n                    </p>\n                    <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555;\">\n                      [Description courte]\n                    </p>\n                    <a href=\"https://exemple.com/document\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; font-size: 14px; font-weight: 600; text-decoration: none;\">\n                      Voir le document en ligne →\n                    </a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "AGENDA / ÉVÉNEMENTS À VENIR",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Événements à venir\n              </h2>\n              <!-- Événement 1 -->\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 0 10px 0; background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px;\">\n                <tr>\n                  <td style=\"padding: 12px;\">\n                    <p style=\"margin: 0 0 3px 0; font-size: 14px; font-weight: 600; color: #003366;\">\n                      [Nom de l'événement]\n                    </p>\n                    <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                      Date : [Date] | Horaire : [Horaire] | Lieu : [Lieu]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n              <!-- Événement 2 -->\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 0 10px 0; background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px;\">\n                <tr>\n                  <td style=\"padding: 12px;\">\n                    <p style=\"margin: 0 0 3px 0; font-size: 14px; font-weight: 600; color: #003366;\">\n                      [Nom de l'événement]\n                    </p>\n                    <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                      Date : [Date] | Horaire : [Horaire] | Lieu : [Lieu]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "BANNIÈRE PROMOTIONNELLE",
    "html": "<tr>\n            <td style=\"padding: 0 0 20px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #003366; border-radius: 8px;\">\n                <tr>\n                  <td style=\"padding: 25px 30px; text-align: center;\">\n                    <p style=\"margin: 0 0 10px 0; font-size: 18px; font-weight: 700; color: #ffffff;\">\n                      [TITRE DE LA PROMOTION]\n                    </p>\n                    <p style=\"margin: 0 0 15px 0; font-size: 14px; color: #e0e0e0; line-height: 1.5;\">\n                      [Description courte de l'offre ou de l'événement]\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\">\n                      <tr>\n                        <td align=\"center\" style=\"background-color: #ffffff; border-radius: 6px;\">\n                          <a href=\"https://exemple.com\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 10px 24px; font-size: 14px; font-weight: 600; color: #003366; text-decoration: none; border-radius: 6px;\">\n                            En savoir plus\n                          </a>\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "TÉMOIGNAGE",
    "html": "<tr>\n            <td style=\"padding: 0 0 20px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #f9f9f9; border-radius: 8px; overflow: hidden;\">\n                <tr>\n                  <td style=\"padding: 20px 30px;\">\n                    <p style=\"margin: 0 0 10px 0; font-size: 15px; color: #333333; font-style: italic; line-height: 1.6;\">\n                      « [Citation du témoignage] »\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                      <tr>\n                        <td width=\"40\" valign=\"top\">\n                          <img src=\"https://picsum.photos/40/40?random=5\" alt=\"Photo de [Nom]\" style=\"display: block; width: 40px; height: 40px; border-radius: 50%; object-fit: cover;\" width=\"40\" height=\"40\" />\n                        </td>\n                        <td valign=\"top\" style=\"padding-left: 10px;\">\n                          <p style=\"margin: 0; font-size: 14px; font-weight: 600; color: #003366;\">\n                            [Prénom] [Nom]\n                          </p>\n                          <p style=\"margin: 0; font-size: 12px; color: #777777;\">\n                            [Fonction / Service]\n                          </p>\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "PARTENAIRES",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #f0f5ff; border-radius: 8px; overflow: hidden;\">\n                <tr>\n                  <td style=\"padding: 20px 30px; text-align: center;\">\n                    <p style=\"margin: 0 0 10px 0; font-size: 16px; font-weight: 600; color: #003366;\">\n                      Partenariat avec [Nom de l'organisation]\n                    </p>\n                    <p style=\"margin: 0 0 15px 0; font-size: 14px; color: #555555; line-height: 1.5;\">\n                      [Description du partenariat ou de l'alliance]\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\">\n                      <tr>\n                        <td style=\"padding: 0 10px;\">\n                          <img src=\"https://picsum.photos/100/50?random=6\" alt=\"Logo partenaire 1\" style=\"display: block; max-width: 100px; height: auto; opacity: 0.7;\" width=\"100\" />\n                        </td>\n                        <td style=\"padding: 0 10px;\">\n                          <img src=\"https://picsum.photos/100/50?random=7\" alt=\"Logo partenaire 2\" style=\"display: block; max-width: 100px; height: auto; opacity: 0.7;\" width=\"100\" />\n                        </td>\n                        <td style=\"padding: 0 10px;\">\n                          <img src=\"https://picsum.photos/100/50?random=8\" alt=\"Logo partenaire 3\" style=\"display: block; max-width: 100px; height: auto; opacity: 0.7;\" width=\"100\" />\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "CHIFFRES / STATISTIQUES",
    "html": "<tr>\n            <td style=\"padding: 0 30px 20px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Chiffres clés\n              </h2>\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n                <tr>\n                  <td width=\"33%\" valign=\"top\" style=\"text-align: center; padding: 10px;\">\n                    <p style=\"margin: 0; font-size: 28px; font-weight: 700; color: #003366;\">\n                      [XX]\n                    </p>\n                    <p style=\"margin: 5px 0 0 0; font-size: 13px; color: #555555;\">\n                      [Description du chiffre]\n                    </p>\n                  </td>\n                  <td width=\"33%\" valign=\"top\" style=\"text-align: center; padding: 10px;\">\n                    <p style=\"margin: 0; font-size: 28px; font-weight: 700; color: #003366;\">\n                      [XX]\n                    </p>\n                    <p style=\"margin: 5px 0 0 0; font-size: 13px; color: #555555;\">\n                      [Description du chiffre]\n                    </p>\n                  </td>\n                  <td width=\"33%\" valign=\"top\" style=\"text-align: center; padding: 10px;\">\n                    <p style=\"margin: 0; font-size: 28px; font-weight: 700; color: #003366;\">\n                      [XX]\n                    </p>\n                    <p style=\"margin: 5px 0 0 0; font-size: 13px; color: #555555;\">\n                      [Description du chiffre]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>"
  },
  {
    "label": "PIED DE PAGE",
    "html": "<tr>\n            <td style=\"background-color: #f8f8f8; padding: 15px 30px; text-align: center;\">\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                [NOM DE LA MISSION / SERVICE]<br />\n                Université de Strasbourg\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none;\">scienceouverte.unistra.fr</a>\n              </p>\n              <p style=\"margin: 0; font-size: 10px; color: #bbbbbb; line-height: 1.4;\">\n                Vous recevez cet email car vous êtes inscrit(e) à notre newsletter.<br />\n                <a href=\"[LIEN_DE_DESINSCRIPTION]\" target=\"_blank\" rel=\"noopener\" style=\"color: #999999; text-decoration: underline;\">Se désinscrire</a>\n              </p>\n            </td>\n          </tr>"
  }
];
