window.EMAIL_TEMPLATES = [
  {
    "id": "cafe",
    "title": "Café science ouverte",
    "description": "Invitation à une session ou un événement",
    "blocks": [
      "<tr>\n            <td style=\"background-color: #8dd3f6; padding: 0;\">\n              <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"display: block; text-align: center; padding: 20px 20px 15px 20px;\">\n                <img src=\"https://scienceouverte.unistra.fr/websites/_processed_/6/7/csm_Logo_cafes_SO_COURT_542485d502.jpg\" alt=\"Logo de l'Université de Strasbourg\" style=\"display: block; margin: 0 auto; max-width: 150px; height: auto; border: 0;\" width=\"150\" />\n              </a>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 25px 30px 10px 30px; text-align: center;\">\n              <h1 style=\"margin: 0; font-size: 22px; font-weight: 700; color: #003366; line-height: 1.3;\">\n                Le prochain café science ouverte\n              </h1>\n              <p style=\"margin: 5px 0 0 0; font-size: 14px; color: #555555; font-weight: 400;\">\n                [NOM DU SERVICE] - Université de Strasbourg\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 10px 30px 30px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Rejoignez-nous au café science ouverte !\n              </h2>\n              <p style=\"margin: 0 0 15px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                Vous souhaitez en savoir plus sur la science ouverte et prolonger votre expérience ? Voici les informations pour le prochain café science ouverte, ouvert à toutes et tous sans inscription :\n              </p>\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 0 15px 0; background-color: #f0f5ff; border-left: 4px solid #003366; border-radius: 4px;\">\n                <tr>\n                  <td style=\"padding: 15px;\">\n                    <!-- Conteneur flex pour aligner le texte et le logo sur la même ligne -->\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n                      <tr>\n                        <td style=\"vertical-align: middle; padding-right: 10px;\">\n                          <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                            [TITRE DE LA SESSION]\n                          </p>\n                          <p style=\"margin: 0 0 5px 0; font-size: 14px; color: #555555;\">\n                            [DATE DE LA SESSION] &nbsp;|&nbsp; [HORAIRE] &nbsp;|&nbsp; En ligne (<a href=\"https://exemple.fr/connexion\">lien de connexion</a>)\n                          </p>\n                        </td>\n                        <td style=\"vertical-align: middle; text-align: right; width: 100px;\">\n                          <!-- LOGO DE L’ÉVÉNEMENT -->\n                          <img src=\"https://via.placeholder.com/80x80.png?text=Logo\" alt=\"Logo de l’événement\" style=\"max-width: 80px; height: auto; display: block; margin: 0 auto;\" width=\"80\" />\n                        </td>\n                      </tr>\n                    </table>\n                    \n                    <p style=\"margin: 10px 0 0 0; font-size: 14px; color: #555555; line-height: 1.5;\">\n                      [DESCRIPTION DE LA SESSION]\n                    </p>\n                  </td>\n                </tr>\n              </table>\n              <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777; \">\n                <br>Cette session est accessible sans inscription préalable, il vous suffit d'utiliser le lien ci-dessus.\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 0 0 20px 0;\">\n              <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0; background-color: #003366; border-radius: 8px;\">\n                <tr>\n                  <td style=\"padding: 25px 30px; text-align: center;\">\n                    <p style=\"margin: 0 0 10px 0; font-size: 18px; font-weight: 700; color: #ffffff;\">\n                      En savoir plus\n                    </p>\n                    <p style=\"margin: 0 0 15px 0; font-size: 14px; color: #e0e0e0; line-height: 1.5;\">\n                      Pour consulter toutes les informations et en savoir plus, cliquez sur le lien ci-dessous qui vous renverra vers l'actualité Ernest.\n                    </p>\n                    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\">\n                      <tr>\n                        <td align=\"center\" style=\"background-color: #ffffff; border-radius: 6px;\">\n                          <a href=\"https://exemple.fr/actualite\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 10px 24px; font-size: 14px; font-weight: 600; color: #003366; text-decoration: none; border-radius: 6px;\">\n                            En savoir plus\n                          </a>\n                        </td>\n                      </tr>\n                    </table>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 0 30px;\">\n              <hr style=\"border: none; border-top: 1px solid #e0e0e0;\" />\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 25px 30px 10px 30px;\">\n              <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777; \">\n                Au plaisir de vous y retrouver, et en vous souhaitant une agréable semaine,<br>Bien cordialement,\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                <br>[NOM / INTERVENANT·E] & [NOM / INTERVENANT·E]\n              </p>\n              <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555; line-height: 1.5;\">\n                <i>Respectivement :</i><br>Chargé de coordination de la politique de science ouverte <br>Administratrice des données de recherche\n              </p>\n              <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                ✉️ <a href=\"mailto:[ADRESSE EMAIL DU SERVICE]\" style=\"color: #003366; text-decoration: none;\">[ADRESSE EMAIL DU SERVICE]</a>\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"background-color: #f8f8f8; padding: 15px 30px; text-align: center;\">\n              <p style=\"margin: 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                [NOM DU SERVICE] <br> Université de Strasbourg<br />\n                <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none;\">scienceouverte.unistra.fr</a>\n              </p>\n            </td>\n          </tr>"
    ]
  },
  {
    "id": "convocation",
    "title": "Convocation de formation",
    "description": "Convocation et informations pratiques",
    "blocks": [
      "<tr>\n            <td style=\"background-color: #8dd3f6; padding: 0;\">\n              <a href=\"https://scienceouverte.unistra.fr/formations/open-access-month/\" target=\"_blank\" rel=\"noopener\" style=\"display: block; text-align: center; padding: 20px 20px 15px 20px;\">\n                <img src=\"https://scienceouverte.unistra.fr/websites/science-ouverte/science_ouverte/visuels_24/cobolet_rs-3__1_.jpg\" style=\"display: block; margin: 0 auto; max-width: 300px; height: auto; border: 0;\" width=\"300\" />\n              </a>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 25px 30px 10px 30px; text-align: center;\">\n              <h1 style=\"margin: 0; font-size: 22px; font-weight: 700; color: #003366; line-height: 1.3;\">\n                [TITRE DE LA FORMATION]              </h1>\n              <p style=\"margin: 5px 0 0 0; font-size: 14px; color: #555555; font-weight: 400;\">\n                Convocation et informations pratiques\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 30px 30px 10px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Convocation à votre formation\n              </h2>\n              <p style=\"margin: 0 0 15px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                Bonjour,<br /> <br />Vous êtes inscrit·e à la session suivante dans le cadre de l’[NOM DE LA CAMPAGNE]. J'ai le plaisir de vous faire parvenir votre convocation.\n                <br /><br />\n                <center><b>[TITRE DE LA FORMATION]</b><br />[DATE DE LA SESSION] [HORAIRE]<br />[NOM / INTERVENANT·E] & [NOM / INTERVENANT·E]<br />[MODALITÉS ET LIEU]</center>\n                <br /><br />\n\n                En cas d’empêchement, merci de nous prévenir <b>au plus vite</b> par retour de mail afin de libérer votre place.\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 0px 30px 10px 30px;\">\n              <p style=\"margin: 0 0 10px 0; font-size: 14px; color: #777777;\">\n                Au plaisir de vous retrouver, et en vous souhaitant une agréable semaine,<br />\n                Bien cordialement,\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 15px; font-weight: 600; color: #003366;\">\n                [NOM / INTERVENANT·E]\n              </p>\n              <p style=\"margin: 0 0 10px 0; font-size: 13px; color: #555555; line-height: 1.5;\">\n                Chargé de coordination de la politique de science ouverte\n              </p>\n              <p style=\"margin: 0; font-size: 13px; color: #555555;\">\n                Tel. : +33 (0)3 68 85 31 78 | <a href=\"mailto:[ADRESSE EMAIL]\" style=\"color: #003366; text-decoration: none;\">[ADRESSE EMAIL]</a>\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 20px 30px;\">\n              <hr style=\"border: none; border-top: 1px solid #e0e0e0;\" />\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"background-color: #f8f8f8; padding: 15px 30px; text-align: center;\">\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                [NOM DU SERVICE]<br />\n                [DIRECTION / SERVICE]<br />\n                Université de Strasbourg\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none;\">scienceouverte.unistra.fr</a>\n              </p>\n              <p style=\"margin: 0; font-size: 10px; color: #bbbbbb; line-height: 1.4;\">\n                Vous recevez cet email car vous vous êtes inscrit·e à l'[NOM DE LA CAMPAGNE].<br />              </p>\n            </td>\n          </tr>"
    ]
  },
  {
    "id": "retour-absent",
    "title": "Retour après absence",
    "description": "Questionnaire et ressources après une absence",
    "blocks": [
      "<tr>\n            <td style=\"background-color: #8dd3f6; padding: 0;\">\n              <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"display: block; text-align: center; padding: 20px 20px 15px 20px;\">\n                <img src=\"https://scienceouverte.unistra.fr/websites/science-ouverte/science_ouverte/visuels_24/cobolet_rs-3__1_.jpg\" style=\"display: block; margin: 0 auto; max-width: 300px; height: auto; border: 0;\" width=\"300\" />\n              </a>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 25px 30px 10px 30px; text-align: center;\">\n              <h1 style=\"margin: 0; font-size: 22px; font-weight: 700; color: #003366; line-height: 1.3;\">\n                Diffuser ses travaux en accès ouvert à l'Unistra\n              </h1>\n              <p style=\"margin: 5px 0 0 0; font-size: 14px; color: #555555; font-weight: 400;\">\n                Mieux comprendre votre désistement\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 30px 30px 10px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Vous nous avez manqué !\n              </h2>\n              <p style=\"margin: 0 0 15px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                Bonjour, <br>vous étiez inscrit·e à l’une de nos sessions de formation, mais n’avez finalement pas pu y participer : <b>[NOM DE LA SESSION]</b>.<br /><br />\n                Parce qu’un imprévu, un agenda chargé ou une contrainte de dernière minute peuvent vite arriver, nous aimerions simplement mieux comprendre ce qui vous a empêché de participer.\n                Nous vous proposons pour cela un questionnaire très court (moins d’une minute).\n                <br /><br />\n                Pour néanmoins en savoir plus sur les accords avec les éditeurs, consultez <a href=\"https://scienceouverte.unistra.fr/publications/accords-avec-clauses-science-ouverte/\">le site web science ouverte de l'Université</a>.\n                <br /><br />\n                Vos réponses nous aideront notamment à voir si nous pouvons mieux adapter les horaires, les modalités ou l’organisation de nos prochaines sessions.</b>.\n              </p>\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                <tr>\n                  <td align=\"center\" style=\"background-color: #003366; border-radius: 6px;\">\n                    <a href=\"https://exemple.fr/questionnaire\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 12px 28px; font-size: 15px; font-weight: 600; color: #ffffff; text-decoration: none; border-radius: 6px;\">\n                      Remplir le questionnaire\n                    </a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 20px 30px;\">\n              <hr style=\"border: none; border-top: 1px solid #e0e0e0;\" />\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"background-color: #f8f8f8; padding: 15px 30px; text-align: center;\">\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                [NOM DU SERVICE]<br />\n                Université de Strasbourg\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none;\">scienceouverte.unistra.fr</a>\n              </p>\n              <p style=\"margin: 0; font-size: 10px; color: #bbbbbb; line-height: 1.4;\">\n                Vous recevez cet email car vous vous êtes inscrit·e à l'[NOM DE LA CAMPAGNE].<br />              </p>\n            </td>\n          </tr>"
    ]
  },
  {
    "id": "retour-participant",
    "title": "Retour après participation",
    "description": "Remerciements et questionnaire de satisfaction",
    "blocks": [
      "<tr>\n            <td style=\"background-color: #8dd3f6; padding: 0;\">\n              <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"display: block; text-align: center; padding: 20px 20px 15px 20px;\">\n                <img src=\"https://scienceouverte.unistra.fr/websites/science-ouverte/science_ouverte/visuels_24/cobolet_rs-3__1_.jpg\" style=\"display: block; margin: 0 auto; max-width: 300px; height: auto; border: 0;\" width=\"300\" />\n              </a>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 25px 30px 10px 30px; text-align: center;\">\n              <h1 style=\"margin: 0; font-size: 22px; font-weight: 700; color: #003366; line-height: 1.3;\">\n                Diffuser ses travaux en accès ouvert à l'Unistra\n              </h1>\n              <p style=\"margin: 5px 0 0 0; font-size: 14px; color: #555555; font-weight: 400;\">\n                Votre avis nous est précieux !\n              </p>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 30px 30px 10px 30px;\">\n              <h2 style=\"margin: 0 0 15px 0; font-size: 18px; font-weight: 600; color: #003366; border-bottom: 3px solid #003366; padding-bottom: 8px;\">\n                Votre avis nous est précieux\n              </h2>\n              <p style=\"margin: 0 0 15px 0; font-size: 15px; color: #333333; line-height: 1.6;\">\n                Bonjour et merci d'avoir participé à la session <b>[NOM DE LA SESSION]</b>.<br /><br />\n                Pour en savoir plus sur les accords avec les éditeurs, consultez <a href=\"https://scienceouverte.unistra.fr/publications/accords-avec-clauses-science-ouverte/\">le site web Science ouverte de l'Université</a>.\n                <br /><br /> Vous souhaitez une <b>attestation de participation</b> à cette session ? N 'hésitez pas à en faire la demande par simple retour à ce mail.\n                <br /><br />\n                Votre retour nous aide à améliorer nos contenus et à répondre au mieux à vos besoins. <b>Si ce n'est pas déjà fait, prenez quelques instants pour remplir ce court questionnaire</b>.\n              </p>\n              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0;\">\n                <tr>\n                  <td align=\"center\" style=\"background-color: #003366; border-radius: 6px;\">\n                    <a href=\"https://exemple.fr/questionnaire\" target=\"_blank\" rel=\"noopener\" style=\"display: inline-block; padding: 12px 28px; font-size: 15px; font-weight: 600; color: #ffffff; text-decoration: none; border-radius: 6px;\">\n                      Remplir le questionnaire\n                    </a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"padding: 20px 30px;\">\n              <hr style=\"border: none; border-top: 1px solid #e0e0e0;\" />\n            </td>\n          </tr>",
      "<tr>\n            <td style=\"background-color: #f8f8f8; padding: 15px 30px; text-align: center;\">\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                [NOM DU SERVICE]<br />\n                [DIRECTION / SERVICE]<br />\n                Université de Strasbourg\n              </p>\n              <p style=\"margin: 0 0 5px 0; font-size: 11px; color: #999999; line-height: 1.5;\">\n                <a href=\"https://scienceouverte.unistra.fr/\" target=\"_blank\" rel=\"noopener\" style=\"color: #003366; text-decoration: none;\">scienceouverte.unistra.fr</a>\n              </p>\n              <p style=\"margin: 0; font-size: 10px; color: #bbbbbb; line-height: 1.4;\">\n                Vous recevez cet email car vous vous êtes inscrit·e à l'[NOM DE LA CAMPAGNE].<br />              </p>\n            </td>\n          </tr>"
    ]
  }
];
